language: python
python:
  - "3.5"
  - "3.6"

services: postgresql

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1

install:
  - pip install -I Django==$DJANGO_VERSION
  - pip install psycopg2-binary==2.7.5

before_script:
  - psql -c "create database testdb;" -U postgres

script:
  - python manage.py test